novaSoft/Models/Eleve.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace novaSoft.Models
{

	
    public class Eleve
    {
        public long eleveId { get; set; }

        /*[DisplayName("Artist")]*/
        [Required(ErrorMessage = "Le nom est obligatoire", AllowEmptyStrings = false)]
		[MinLength(3)]
        /*[Required]*/
        public string eleveName { get; set; }

		[Required(ErrorMessage = "Le prénom  est obligatoire", AllowEmptyStrings = false)]
		public string eleveFirstName { get; set; }
		/*public DateTime eleveBirthdate { get; set; }*/
		[Required(ErrorMessage = "Le sexe est obligatoire", AllowEmptyStrings = false)]
		public string eleveSexe { get; set; }
		[Required(ErrorMessage = "Le lieu de naissance  est obligatoire", AllowEmptyStrings = false)]
		public string elevePlaceOfBirth { get; set; }
		[Required(ErrorMessage = "Le l'adresse de l'élève est obligatoire", AllowEmptyStrings = false)]
		public string eleveAddress { get; set; }
		public string elevePhoneNumber { get; set; }

		[Required(ErrorMessage = "La classe est obligatoire", AllowEmptyStrings = false)]
		public string eleveClasse { get; set; }

		public string eleveMatricule { get; set; }
		[Required(ErrorMessage = "Merci de choisir une serie ou un cycle", AllowEmptyStrings = false)]
		public string eleveSerie { get; set; }

		

		/*[Required]*/
		public string elevePassword { get; set; }
		public string eleveUserName { get; set; }


		[Required(ErrorMessage = "Le nom du père est obligatoire", AllowEmptyStrings = false)]
		public string eleveDadName { get; set; }
		[Required(ErrorMessage = "Le prénom du père est obligatoire", AllowEmptyStrings = false)]
		public string eleveDadFirstname { get; set; }
		public string eleveDadCinNum { get; set; }
		public string eleveDadProfession { get; set; }
		[Required(ErrorMessage = "La résidence du père est obligatoire", AllowEmptyStrings = false)]
		public string eleveDadResidence { get; set; }
		
		public string eleveDadPhoneNum { get; set; }
		[Required]
		public string eleveMomName { get; set; }
		[Required]
		public string eleveMomFirstname { get; set; }
		public string eleveMomCinNum { get; set; }
		public string eleveMomProfession { get; set; }
		public string eleveMomResidence { get; set; }
		public string eleveMomPhoneNum { get; set; }

		[Required]
		public string eleveTutorName { get; set; }
		[Required]
		public string eleveTutorFirstname { get; set; }
		public string eleveTutorCinNum { get; set; }
		[Required]
		public string eleveTutorProfession { get; set; }
		[Required]
		public string eleveTutorResidence { get; set; }
		[Required]
		public string eleveTutorPhoneNum { get; set; }

		public List<Paiements> paiements {

			get; set;
		}
		public List<Fratrie> fratrie { get; set; }
	}

	
}

novaSoft/Controllers/EleveController.cs
using novaSoft.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace novaSoft.Controllers
{
    public class EleveController : Controller
    {
        // GET: Eleve
        public ActionResult Index()
        {

            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:8081/eleve/");
            Client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = Client.GetAsync("all").Result;

            if (response.IsSuccessStatusCode)
            {
                ViewBag.result = response.Content.ReadAsAsync<IEnumerable<Eleve>>().Result;

            }
            else
            {
                ViewBag.result = "error haha";
            }
            return View();
        }

        
       
        [HttpGet]
        public ActionResult RechercheEleve(string elevSeacrh)
        {

            HttpClient client = new HttpClient();
            HttpResponseMessage resp = client.GetAsync("http://localhost:8081/eleve/Search/"+elevSeacrh).Result;

            if (resp.IsSuccessStatusCode)
            {
                ViewBag.result = resp.Content.ReadAsAsync<Eleve>().Result;
            }
            else
            {
                ViewBag.result = "ERROR ah ahahhh"+ elevSeacrh;
            }

            return View("RechercheEleve");
        }

        // GET: Eleve/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        

        // GET: Eleve/Create
        [HttpGet]
        public ActionResult Create()
        {

            return View();
        }

        // POST: Eleve/Create
        [HttpPost]
        public async Task<ActionResult> Create(Eleve eleve)
        {
            if (ModelState.IsValid)
            {
                HttpClient client = new HttpClient();
                client.BaseAddress = new Uri("http://localhost:8081/eleve/");

                await client.PostAsJsonAsync<Eleve>("add", eleve).ContinueWith((postTask) => postTask.Result.EnsureSuccessStatusCode());


                HttpResponseMessage response = (await client.GetAsync("LastEleveId"));

                if (response.IsSuccessStatusCode)
                {
                    ViewBag.result = response.Content.ReadAsAsync<Eleve>().Result;

                    long Eleveid = ViewBag.result.eleveId;

                    return RedirectToAction("EleveContent/" + Eleveid);

                }
                else
                {
                    ViewBag.result = "error haha";
                    return RedirectToAction("EleveContent/" + 1);
                }

            }
            return View();


        }



    // GET: Eleve/Edit/5
    public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Eleve/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Eleve/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Eleve/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }



        public  async Task<ActionResult> EleveContent(long id)
        {
            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:8081/eleve/");
            /*
                        Client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            */
            HttpResponseMessage response =  (await Client.GetAsync("http://localhost:8081/eleve/"+ id));

            
            if (response.IsSuccessStatusCode)
            {

                ViewBag.result =  response.Content.ReadAsAsync<Eleve>().Result;
            }
            else
            {
                ViewBag.result = "Une erreur s'est produite";
            }


            return View("EleveContent");
        }

        [HttpGet]
       public ActionResult Search(string searchingValue)
        {
            
            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:8081/eleve/");
            Client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage resp = Client.GetAsync("Search/" + searchingValue).Result;





            if (resp.IsSuccessStatusCode)
            {
                ViewBag.result = resp.Content.ReadAsAsync<IEnumerable<Eleve>>().Result;
            }
            else
            {
                ViewBag.result = "ERROR ah ahahhh" + searchingValue;
            }

            return View("Search");
        }

        [HttpGet]
        public ActionResult updatePaiement(int id, string paiementMois, int montant)
        {
            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:8081/Paiement/");

            Client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpResponseMessage resp = Client.GetAsync("update/" + id + "/" + paiementMois + "/" + montant).Result;

            if (resp.IsSuccessStatusCode)
            {
                ViewBag.resp = resp.Content.ReadAsAsync<Paiements>().Result;

                return View("updatePaiement");

            }

            else
            {
                ViewBag.result = "error haha";
                return View("updatePaiement");
            }

       
        }


    }


}

novaSoft/Views/Eleve/Search.cshtml
@{
    ViewBag.Title = "Search";
}

<h2>@ViewBag.a</h2>


@{
    @* @Html.TextBox("searchingValue")*@


    @* A reutiliser si possible   <form>

            <div style="height:35px; width:100%; display:flex;flex-direction:row">

                <input type="text" placeholder="Rechercher" style="min-width:50%;height:35px" />


                <button type="submit" style="border:none ;outline:1px solid blue;background:red; height: 35px;width:100px; display: flex; justify-content: center; flex-direction: column">

                    <svg style="margin-left:23.5px" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                    </svg>

                </button>

            </div>

        </form>*@



}

<div style="height:35px; width:100%; display:flex;flex-direction:row">

    <input type="text" placeholder="Rechercher" name="a" id="seacrhVal" style="min-width:50%;height:35px" />


    <button onclick="sendData()" style="border:none ;outline:1px solid blue;background:red; height: 35px;width:100px; display: flex; justify-content: center; flex-direction: column">

        <svg style="margin-left:23.5px" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
        </svg>

    </button>

</div>


<script>
    function sendData() {
        var inp = document.getElementById('seacrhVal').value;
        document.location.href = "https://localhost:44312/Eleve/Search/" + inp;

    }

    var seacrhVal = document.getElementById("seacrhVal");
    seacrhVal.addEventListener("keydown", function (e) {
        if (e.keyCode === 13) {
            var inp = document.getElementById('seacrhVal').value;
            document.location.href = "https://localhost:44312/Eleve/Search/" + inp;
        }
    });


</script>

<!--
{

    <div style="background-color:red; display:flex; flex-direction:row;justify-content:space-between; width:60%;">-->
@*
    @Html.TextBoxFor(model => model.eleveMatricule, new { @class = "name", @placeholder = "Rechercher", @style = "outline:none; height:35px; border:none; padding-left:15px" })
*@

<!--<input type="submit" value="Search" />-->
@*<button type="submit" style="border:none ;outline:1px solid blue;background:red; height: 35px;width:100px; display: flex; justify-content: center; flex-direction: column">
        <svg style="margin-left:23.5px" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
        </svg>
    </button>*@

<!--</div>
}-->
@*<hr />*@
<br />




@{
    if (ViewBag.result.Count <= 1)
    {
        <p> @ViewBag.result.Count elève trouvé</p>
    }
    else
    {
       
          <p> @ViewBag.result.Count elèves trouvés</p>
     

    }
}


<br />

<div style="        width: 100%;
            height: auto;
            min-height: 100vh;
            display: flex;
            flex-wrap: wrap;
            background: white;
            padding: 25px;
            box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px;
    ">



    @foreach (var p in ViewBag.result)
    {
        <div style=" background:white;padding: 5px; max-height:210px; height: auto;min-width: 200px;margin-left: 15px; margin-top: 15px;box-shadow: rgba(0, 0, 0, 0.25) 0px 0.0625em 0.0625em, rgba(0, 0, 0, 0.25) 0px 0.125em 0.5em, rgba(255, 255, 255, 0.1) 0px 0px 0px 1px inset; ">


            <div id="profilPhoto" style="height:42px; width: 42px;background: #7200c3; border-radius: 5px; margin:10px">
                <label class="infoNom"><a href="@Url.Action("EleveContent")/@p.eleveId"> @p.eleveName @p.eleveFirstName </a> </label>
                <label class="infoNom" style="margin-top:22px;color:#c6c6c6">@p.eleveClasse @p.eleveSerie</label>
            </div>

            <br />


            <div style="height:auto; width:100%; padding: 10px;">

                <label class="eleveInfo">
                    <img class="iconeEleve" src="https://icons.veryicon.com/png/o/business/multi-color-financial-and-business-icons/dollar-15.png" /> Dernier paiement
                </label><br />
                <label class="eleveInfo">
                    <img class="iconeEleve" src="https://www.icone-png.com/png/19/19043.png" /> Dernier montant
                </label><br />

            </div>

        </div>

    }

</div>


<style>

    a {
        text-decoration: none;
    }

    .infoNom {
        position: absolute;
        margin-left: 50px;
        margin-top: 7px;
        font-size: 12px;
    }

    .eleveInfo {
        font-size: smaller;
        color: #b6b6b6;
    }

    .iconeEleve {
        width: 17px;
        height: 17px;
    }
</style>

novaSoft/Views/Eleve/index.cshtml
<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>

<body>

    @model novaSoft.Models.Eleve
    <div style="        height: 100vh;
        width: 100%;
        background: #d9e8b3;
">

        <div style="        height: 150px;
        margin-top: 50px;
        width: 100%;
        padding: 25px;

  ">
            <h2 style="color:black;">Gestion d'élèves</h2>
            <br />

            @* <a style="font-size:20px; margin-top:50px;" href="@Url.Action("Create","Eleve")">Ajouter un nouveau élève</a>*@

            <br />



            


        </div>



        <br /><br />




              <div style="        width: 100%;
        height: auto;
        min-height: 100vh;
        display: flex;
        flex-wrap: wrap;
        background: white;
        padding: 25px;
        box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px;
">
                  

                      @foreach (var p in ViewBag.result)
                      {


                          <div style=" background:white;padding: 5px; max-height:210px; height: auto;min-width: 200px;margin-left: 15px; margin-top: 15px;box-shadow: rgba(0, 0, 0, 0.25) 0px 0.0625em 0.0625em, rgba(0, 0, 0, 0.25) 0px 0.125em 0.5em, rgba(255, 255, 255, 0.1) 0px 0px 0px 1px inset; ">


                              <div id="profilPhoto" style="height:42px; width: 42px;background: #7200c3; border-radius: 5px; margin:10px">
                                  <label class="infoNom"><a href="@Url.Action("EleveContent")/@p.eleveId"> @p.eleveName @p.eleveFirstName </a> </label>
                                  <label class="infoNom" style="margin-top:22px;color:#c6c6c6">@p.eleveClasse @p.eleveSerie</label>
                              </div>

                              <br />


                              <div style="height:auto; width:100%; padding: 10px;">

                                  <label class="eleveInfo">
                                      <img class="iconeEleve" src="https://icons.veryicon.com/png/o/business/multi-color-financial-and-business-icons/dollar-15.png" /> Dernier paiement
                                  </label><br />
                                  <label class="eleveInfo">
                                      <img class="iconeEleve" src="https://www.icone-png.com/png/19/19043.png" /> Dernier montant
                                  </label><br />

                              </div>

                          </div>

                      }
                  



              </div>


    </div>


    <style>

        a {
            text-decoration: none;
        }

        .infoNom {
            position: absolute;
            margin-left: 50px;
            margin-top: 7px;
            font-size: 12px;
        }

        .eleveInfo {
            font-size: smaller;
            color: #b6b6b6;
        }

        .iconeEleve {
            width: 17px;
            height: 17px;
        }
    </style>


</body>
</html>

novaSoft/Views/Eleve/updatePaiement.cshtml
@{
    ViewBag.Title = "updatePaiement";
}

<h2>updatePaiement</h2>